//
// Created by andrey on 02.12.16.
//

#ifndef DATA_TRANSMISSION_SHEDULE_EXCEPTIONS_H
#define DATA_TRANSMISSION_SHEDULE_EXCEPTIONS_H

enum Exception {
	OPEN_FILE_ERROR,
	JOB_WORKED_TIME_EXPIRED,
};
#endif //DATA_TRANSMISSION_SHEDULE_EXCEPTIONS_H
