//
// Created by andrey on 02.12.16.
//

#ifndef DATA_TRANSMISSION_SHEDULE_EXCEPTIONS_H
#define DATA_TRANSMISSION_SHEDULE_EXCEPTIONS_H

enum Exception {
	OPEN_FILE_ERROR,
	
	NULL_POINTER,
	
	WRONG_CRITERIA_VALUE,
	// set time errors
	TIME_OUT_OF_RANGE,
	JOB_WORKED_TIME_EXPIRED,
};
#endif //DATA_TRANSMISSION_SHEDULE_EXCEPTIONS_H
